apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: eks-test
  region: ap-northeast-2
  version: "1.22"
vpc:
  cidr: "192.168.0.0/16"
managedNodeGroups:
  - name: node-group
    instanceType: m5.large
    desiredCapacity: 3
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-backend
  namespace: default
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 2
      maxSurge: 2
  selector:
    matchLabels:
      app: deploy-backend
  template:
    metadata:
      labels:
        app: deploy-backend
    spec:
      containers:
        - name: deploy-backend
          image: 083495778532.dkr.ecr.ap-northeast-2.amazonaws.com/mogle_eks_repo:1.0
          ports:
            - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: deploy-backend
spec:
  type: LoadBalancer
  selector:
    app: deploy-backend
  ports:
    - port: 8080
      targetPort: 5000
      protocol: TCP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: "deploy-ingress"
  namespace: default
spec:
  rules:
    - http:
        paths:
          - path: /contents
            pathType: Prefix
            backend:
              service:
                name: "deploy-backend"
                port:
                  number: 8080

