version: 0.2
phases:
  install:
    commands:
      - aws ecr get-login-password --region ap-northeast-2 | docker login --username AWS --password-stdin 083495778532.dkr.ecr.ap-northeast-2.amazonaws.com
  pre_build:
      commands:
  build:
    commands:
  post_build:
    commands:
      - eksctl create cluster -f build-all.yaml
      - echo "complete"
artifacts:
  files: 
    - '**/*'
